default: &default
  adapter: mysql2
  host: iamdan.me
  username: #CHANGE ME
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: wisp_development

test:
  <<: *default
  database: wisp_test

production:
  <<: *default
  database: wisp_prod
